sudo: false
language: node_js
node_js:
  - '10'
before_install:
  - openssl aes-256-cbc -K $encrypted_12bfbb074edf_key -iv $encrypted_12bfbb074edf_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host ${note_server_host}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - npm install --production
script:
  - npm run ci
after_script:
  - npm install codecov && codecov
addons:
  ssh_known_hosts: "${note_server_host}"
after_success:
  - tar -jcf note-service.tar.bz2 *
  - scp note-service.tar.bz2 ${note_server_username}@${note_server_host}:/home/app/
  - ssh ${note_server_username}@${note_server_host} 'cd /home/app/note-service && yarn stop'
  - ssh ${note_server_username}@${note_server_host} 'cd /home/app && rm -rf ./note-service && mkdir -p note-service && tar -jxf note-service.tar.bz2 -C note-service'
  - ssh ${note_server_username}@${note_server_host} 'cd /home/app/note-service && yarn start'
