sudo: false
language: node_js
node_js:
  - '10'
before_install:
  - openssl aes-256-cbc -K $encrypted_12bfbb074edf_key -iv $encrypted_12bfbb074edf_iv -in id_rsa_deploy.enc -out ~/.ssh/id_rsa_deploy -d
  - chmod 600 ~/.ssh/id_rsa_deploy
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
addons:
  ssh_known_hosts: ${note_server_host}
after_success:
  - npm prune --production
  - tar -jcf note-service.tar.bz2 *
  - scp note-service.tar.bz2 ${note_server_username}@${note_server_host}:/home/app/
  - ssh ${note_server_username}@${note_server_host} 'mkdir -p note-service && tar -jxf note-service.tar.bz2 -C note-service'
  - ssh ${note_server_username}@${note_server_host} 'cd note-service && yarn stop && yarn start'
